# Generated by Django 5.2.7 on 2025-10-26 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='description',
        ),
        migrations.AlterField(
            model_name='saflora_product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
