# Generated by Django 5.2.7 on 2025-10-26 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_feature_description_alter_saflora_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saflora_product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
