# Generated by Django 5.2.7 on 2025-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_saflora_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='saflora_product',
            name='variant',
            field=models.ManyToManyField(null=True, to='Product.variants'),
        ),
    ]
