# Generated by Django 5.2.7 on 2025-10-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_variants_saflora_product_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'variant'},
        ),
        migrations.RenameField(
            model_name='saflora_product',
            old_name='feature',
            new_name='features',
        ),
    ]
