# Generated by Django 5.2.7 on 2025-10-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_variants_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saflora_product',
            name='variant',
            field=models.ManyToManyField(to='Product.variants'),
        ),
    ]
