# Generated by Django 5.2.7 on 2025-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_saflora_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='saflora_product',
            name='fragnence',
            field=models.CharField(choices=[('LEMON', 'lemon'), ('JASMIE', 'Jasmine')], null=True),
        ),
    ]
