# Generated by Django 5.2.7 on 2025-10-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_saflora_product_fragnence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saflora_Base_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(verbose_name='item_name')),
                ('item_image', models.ImageField(upload_to='item_image')),
                ('item_description', models.TextField()),
                ('items_variants', models.ManyToManyField(to='Product.saflora_product')),
            ],
        ),
    ]
