# Generated by Django 5.2.7 on 2025-10-31 05:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_saflora_base_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saflora_base_product',
            options={'verbose_name': 'Saflora item'},
        ),
        migrations.AlterField(
            model_name='saflora_base_product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
