# Generated by Django 5.2.7 on 2025-10-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_saflora_base_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saflora_Base_Product',
        ),
    ]
