# Generated by Django 5.2.7 on 2025-10-31 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_delete_saflora_base_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saflora_Base_Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(verbose_name='item_name')),
                ('item_image', models.ImageField(upload_to='item_image')),
                ('item_description', models.TextField()),
                ('items_variants', models.ManyToManyField(to='Product.saflora_product')),
            ],
            options={
                'verbose_name': 'Saflora item',
            },
        ),
    ]
