# Generated by Django 5.2.7 on 2025-10-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_saflora_base_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saflora_base_product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
