# Generated by Django 5.2.7 on 2025-10-24 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Records',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('INITIATED', 'Initiated'), ('REFUNDED', 'Refunded'), ('USER_CANCLED', 'User canceled'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], verbose_name='Payment Status  ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(choices=[('KHALTI', 'Khalti'), ('ESEWA', 'Esewa')], verbose_name='Payment_Provider')),
                ('pidx', models.CharField(editable=False, max_length=255, verbose_name='Id')),
                ('total_amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=255)),
                ('service_provider_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('INITIATED', 'Initiated'), ('REFUNDED', 'Refunded'), ('USER_CANCLED', 'User canceled'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], verbose_name='Service Provider Status')),
                ('fee', models.FloatField()),
                ('refunded', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.saflora_product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
