# Generated by Django 5.2.7 on 2025-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_records',
            name='fee',
            field=models.FloatField(blank=True),
        ),
    ]
