# Generated by Django 5.2.7 on 2025-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_alter_payment_records_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_records',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
