# Generated by Django 5.2.7 on 2025-10-24 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_payment_records_fee'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_records',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.saflora_product', verbose_name='Product'),
        ),
    ]
