# Generated by Django 5.2.7 on 2025-10-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_payment_records_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_records',
            options={'verbose_name': 'Payment Record'},
        ),
        migrations.AlterField(
            model_name='payment_records',
            name='pidx',
            field=models.CharField(max_length=255, verbose_name='Id'),
        ),
    ]
