# Generated by Django 5.2.7 on 2025-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_payment_records_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_records',
            name='pidx',
            field=models.CharField(max_length=255, verbose_name='PIDX'),
        ),
        migrations.AlterField(
            model_name='payment_records',
            name='service_provider_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('INITIATED', 'Initiated'), ('REFUNDED', 'Refunded'), ('USER_CANCLED', 'User canceled'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('FAILED', 'Failed')], verbose_name='Service Provider Status'),
        ),
        migrations.AlterField(
            model_name='payment_records',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('INITIATED', 'Initiated'), ('REFUNDED', 'Refunded'), ('USER_CANCLED', 'User canceled'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('FAILED', 'Failed')], verbose_name='Payment Status  '),
        ),
    ]
