# Generated by Django 5.2.7 on 2025-10-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_payment_records_pidx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_records',
            name='pidx',
            field=models.CharField(editable=False, max_length=255, verbose_name='PIDX'),
        ),
        migrations.AlterField(
            model_name='payment_records',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
