# Generated by Django 5.2.7 on 2025-11-02 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_rename_shipping_adddress_anonymoususer_shipping_address'),
        ('Payment', '0007_alter_payment_records_pidx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_records',
            name='annoymous_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.anonymoususer'),
        ),
        migrations.AlterField(
            model_name='payment_records',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
