# Generated by Django 5.2.7 on 2025-11-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_payment_records_annoymous_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_records',
            old_name='annoymous_user',
            new_name='anonymous_user',
        ),
    ]
