# Generated by Django 5.2.7 on 2025-11-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_rename_annoymous_user_payment_records_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_records',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cod')], null=True),
        ),
    ]
