# Generated by Django 5.2.7 on 2025-11-03 09:38

import Payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_payment_records_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_records',
            name='payment_session',
            field=models.DateTimeField(default=Payment.models.expires_at),
        ),
    ]
