# Generated by Django 5.2.7 on 2025-11-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_saflora_user_location'),
        ('Payment', '0011_payment_records_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_records',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.cart', verbose_name='Cart'),
        ),
    ]
