# Generated by Django 5.2.7 on 2025-10-18 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 18, 3, 59, 48, 81757, tzinfo=datetime.timezone.utc)),
        ),
    ]
