# Generated by Django 5.2.7 on 2025-10-24 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 24, 3, 34, 1, 857090, tzinfo=datetime.timezone.utc)),
        ),
    ]
