# Generated by Django 5.2.7 on 2025-10-31 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0024_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 31, 7, 49, 41, 189115, tzinfo=datetime.timezone.utc)),
        ),
    ]
