# Generated by Django 5.2.7 on 2025-11-02 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0032_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 10, 40, 52, 187704, tzinfo=datetime.timezone.utc)),
        ),
    ]
