# Generated by Django 5.2.7 on 2025-11-02 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0035_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 2, 11, 8, 20, 974175, tzinfo=datetime.timezone.utc)),
        ),
    ]
