# Generated by Django 5.2.7 on 2025-11-03 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0039_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 3, 43, 59, 119698, tzinfo=datetime.timezone.utc)),
        ),
    ]
