# Generated by Django 5.2.7 on 2025-11-03 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0041_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 9, 43, 29, 861670, tzinfo=datetime.timezone.utc)),
        ),
    ]
