# Generated by Django 5.2.7 on 2025-11-07 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0047_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 8, 16, 39, 547392, tzinfo=datetime.timezone.utc)),
        ),
    ]
