# Generated by Django 5.2.7 on 2025-11-22 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0048_alter_verification_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 2, 57, 43, 203175, tzinfo=datetime.timezone.utc)),
        ),
    ]
