# Generated by Django 5.2.7 on 2025-10-10 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.saflora_product')),
            ],
        ),
        migrations.AddField(
            model_name='saflora_user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='Accounts.cart'),
        ),
    ]
