# Generated by Django 5.2.7 on 2025-10-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_cart_saflora_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='saflora_user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saflora_user',
            name='hear_about_us',
            field=models.CharField(choices=[('friend', 'Friend'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
