# Generated by Django 5.2.7 on 2025-10-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_saflora_user_address_saflora_user_hear_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saflora_user',
            name='hear_about_us',
            field=models.CharField(default='Others', max_length=20),
        ),
    ]
