# Generated by Django 5.2.7 on 2025-10-24 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_saflora_user_hear_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saflora_user',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Saflora_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
