# Generated by Django 5.2.7 on 2025-10-24 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_saflora_user_cart_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('purchased', 'Purchased'), ('wishlist', 'Wishlist')], default='in_cart'),
        ),
    ]
