# Generated by Django 5.2.7 on 2025-10-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_cart_added_at_cart_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('IN_CART', 'In Cart'), ('PURCHASED', 'Purchased'), ('WISHLIST', 'Wishlist')], default='IN_CART'),
        ),
    ]
