# Generated by Django 5.2.7 on 2025-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.CharField(null=True),
        ),
    ]
