# Generated by Django 5.2.7 on 2025-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_cart_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
