# Generated by Django 5.2.7 on 2025-10-31 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_cart_paid_price_cart_total_price'),
        ('Product', '0012_saflora_base_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.saflora_base_product'),
        ),
    ]
