# Generated by Django 5.2.7 on 2025-10-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_cart_item'),
        ('Product', '0012_saflora_base_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.saflora_product'),
        ),
    ]
