# Generated by Django 5.2.7 on 2025-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saflora_user',
            name='address_type',
            field=models.TextField(null=True),
        ),
    ]
