# Generated by Django 5.2.7 on 2025-11-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_saflora_user_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='itahari')),
            ],
            options={
                'verbose_name': 'location',
            },
        ),
        migrations.AddField(
            model_name='saflora_user',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.location'),
        ),
    ]
