# Generated by Django 5.2.7 on 2025-11-02 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_location_saflora_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('shipping_adddress', models.CharField()),
                ('city', models.TextField()),
                ('province', models.CharField()),
                ('postal_code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'anonymous_user',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='annoymous_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.anonymoususer'),
        ),
    ]
