# Generated by Django 5.2.7 on 2025-11-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_anonymoususer_cart_annoymous_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymoususer',
            old_name='shipping_adddress',
            new_name='shipping_address',
        ),
    ]
