# Generated by Django 5.2.7 on 2025-11-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_rename_shipping_adddress_anonymoususer_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cod')], null=True),
        ),
    ]
