# Generated by Django 5.2.7 on 2025-11-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_cart_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='annoymous_user',
            new_name='anonymous_user',
        ),
    ]
