# Generated by Django 5.2.7 on 2025-11-03 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_rename_annoymous_user_cart_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saflora_user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.location'),
        ),
    ]
