# Generated by Django 5.2.7 on 2025-11-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_saflora_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='n/a')),
            ],
            options={
                'verbose_name': 'Province',
            },
        ),
        migrations.AddField(
            model_name='saflora_user',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.province'),
        ),
    ]
