# Generated by Django 5.2.7 on 2025-11-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_province_saflora_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.province'),
        ),
    ]
