# Generated by Django 5.2.7 on 2025-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_alter_anonymoususer_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='saflora_user',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('NEPALI', 'Nepali')], default='ENGLISH', max_length=20),
        ),
    ]
